# -*- coding: utf-8 -*-
"""sortbusinessesbystate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zCn1jJHoi5reg8t63cTnEH_iGQCTHmf4
"""

import pandas as pd

df = pd.read_csv("CBP2022.CB2200CBP-2024-07-31T155233.csv")
naicslist = set(df.loc[:,"2017 NAICS code (NAICS2017)"])
naicslist = list(sorted(naicslist))
naicslist.pop(0)

print(naicslist) #reads the fine then gets all the naics codes and sorts them, removes 00 because that's not needed

colnames = []

for i in range(len(naicslist)):
  colnames.append(naicslist[i] + " - # of bus")
  colnames.append(naicslist[i] + " - # emp")
  colnames.append(naicslist[i] + " - annual payroll")

#adds catagories for all NAICS categories

print(colnames)

states = set(df.loc[:,"Geographic Area Name (NAME)"])
states = list(sorted(states))
print(states) #gets all the states and sorts them alphabetically
print(states[19])

totals = [[[] for _ in range(len(naicslist))] for _ in range(len(states))]
#creates a list by states and then by sector
"""
________________________________________________________________________________
"""
tosearch = df.values.tolist()

for i in range(len(tosearch)):
  if tosearch[i][1] not in naicslist:
    pass
  else:
    naiccode = tosearch[i][1]
    state = tosearch[i][0]
    toappendnaic = naicslist.index(naiccode)
    toappendstate = states.index(state)
    #gets the state and naic code and the index for it to be aggregated
    employees = int(tosearch[i][6].replace(',', ''))
    payroll = int(tosearch[i][7].replace(',', ''))
    if len(totals[toappendstate][toappendnaic]) == 0:
      totals[toappendstate][toappendnaic].append(1)
      totals[toappendstate][toappendnaic].append(employees)
      totals[toappendstate][toappendnaic].append(payroll)
    else:
      totals[toappendstate][toappendnaic][0] += 1
      totals[toappendstate][toappendnaic][1] += int(employees)
      totals[toappendstate][toappendnaic][2] += int(payroll)

#adds the values to each entry for state and naic code

print(totals)

tocsv = []
for i in range(len(totals)):
  subl = []
  for l in range(len(totals[i])):
    for m in range(len(totals[i][l])):
      subl.append(totals[i][l][m])
  tocsv.append(subl)
pd.set_option('display.max_columns', None)

final = pd.DataFrame(tocsv, columns = colnames,  index=states)
final